### ISSUE TITLE
Can't build Release mode binaries

### ISSUE THREAD

**Issue by greenozon** [DestroyerDarkNess/Hydra#27]
on try:

<img width="1904" height="752" alt="Image" src="https://github.com/user-attachments/assets/81145123-81df-4859-a1e8-760fbec9fe36" />

**Comment by DestroyerDarkNess** [comment]
Fixed, download the latest commits from the main branch. 🫡

<img width="843" height="58" alt="Image" src="https://github.com/user-attachments/assets/8563bd74-a3e8-4823-9ffb-de87d4db006f" />

**Comment by greenozon** [comment]
Thanks
I"m still not able to build Release...

in debug mode wnen I do clean/rebuild - all works like a charm:
>========== Rebuild All: 6 succeeded, 0 failed, 0 skipped ==========

in realease:
>========== Rebuild All: 3 succeeded, 3 failed, 0 skipped ==========
